{{- range $name, $crole := .Values.rbac.clusterRoles }}
{{- if not $crole.disabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
rules:
{{- include "vp-rbac.rulesHelper" (list $crole.rules) | nindent 2 }}
{{- end }} {{- /* if not $crole.disabled */}}
{{- end }} {{- /* range */}}
