{{- range $name, $role := .Values.rbac.roles }}
{{- if not $role.disabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $role.namespace }}
rules:
{{- include "vp-rbac.rulesHelper" (list $role.rules) | nindent 2 }}
{{- end }} {{- /* if not $role.disabled */}}
{{- end }} {{- /* range */}}
