{{- range $name, $sa := .Values.rbac.serviceAccounts }}
{{- if not $sa.disabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $sa.namespace }}

{{- range $sa.roleBindings.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $name }}-{{ . }}-rb"
  namespace: {{ $sa.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $sa.namespace }}
roleRef:
  kind: Role
  name: {{ . | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }} {{- /* range roles */}}

{{- range $sa.roleBindings.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $name }}-{{ . }}-crb"
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: {{ $sa.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ . | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }} {{- /* range clusterroles*/}}

{{- end }} {{- /* if $sa.disabled */}}
{{- end }} {{- /* range ServiceAccounts */}}
